spring.application.name=api-gateway
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8762/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway discovery
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator Prometheus (UN SEUL)
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.metrics.export.prometheus.enabled=true
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG