global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'winderp-prometheus:9090'

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'winderp-gateway:8082'
          - 'winderp-auth:8087'
          - 'winderp-dashboard:8088'
          - 'winderp-candidate:8089'
          - 'winderp-notification:8090'
          - 'winderp-interview:8091'
          - 'winderp-eureka:8762'