apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-service
  namespace: recrute
  labels:
    app: interview-service
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: interview-service
  template:
    metadata:
      labels:
        app: interview-service
        tier: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: interview-service
          image: recrute-interview-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: recrute-config
                  key: SPRING_PROFILES_ACTIVE
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: recrute-config
                  key: EUREKA_URI
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_APPLICATION_NAME
              value: "INTERVIEW-SERVICE"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: recrute-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: recrute-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: recrute-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: recrute-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recrute-secrets
                  key: DB_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 90
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: recrute
  labels:
    app: interview-service
spec:
  selector:
    app: interview-service
  ports:
    - port: 8083
      targetPort: 8083
      name: http
      protocol: TCP
  type: ClusterIP