global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['winderp-prometheus:9090']

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 20s
    scrape_timeout: 10s
    static_configs:
      - targets:
          - 'winderp-gateway:8082'
          - 'winderp-auth:8087'
          - 'winderp-notification:8090'
          - 'winderp-eureka:8762'
          - 'winderp-dashboard:8088'   # ajouté
          - 'winderp-candidate:8089'   # ajouté
          - 'winderp-interview:8091'   # ajouté

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['winderp-cadvisor:8080']