global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['localhost:9323']
  
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - 'host.docker.internal:8082'  # API Gateway
        - 'host.docker.internal:8087'  # Auth Service
        - 'host.docker.internal:8089'  # Candidate
        - 'host.docker.internal:8091'  # Interview
        - 'host.docker.internal:8088'  # Dashboard
        - 'host.docker.internal:8090'  # Notification
        - 'host.docker.internal:8762'  # Eureka
        labels:
          job: spring-boot
          tier: microservice

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
        labels:
          service: postgresql

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:9121']
        labels:
          service: redis
